<a href="https://colab.research.google.com/github/arcy405/pytorch_basics/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu118


In [ ]:
# scalar
scalar = torch.tensor(8)
scalar

tensor(8)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

8

In [ ]:
# Vector
vector = torch.tensor([9,9])
vector

tensor([9, 9])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[1,2],
                       [5,7]])
MATRIX

tensor([[1, 2],
        [5, 7]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([5, 7])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,3],
                        [8,2,4]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 3],
         [8, 2, 4]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0,1,1]

tensor(5)

In [ ]:
tensor2 = torch.tensor([[[[[1,2],[4,5],[7,8]]]]])

In [ ]:
tensor2.shape
# tensor2[0,0]

torch.Size([1, 1, 1, 3, 2])

##### Random Tensors ######

In [ ]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1212, 0.0889, 0.2465, 0.3657],
        [0.7572, 0.8370, 0.4308, 0.4482],
        [0.1560, 0.4208, 0.3403, 0.3133]])

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

Zeros and Ones

In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

Creating a range of tensors and tensors like

In [ ]:
# use torch.range()
one_to_ten = torch.arange(start=1, end=11, step =1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [ ]:
# Float 32 tensors
float_32_tensor = torch.tensor([4.8,9.2,8.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([4.8000, 9.2000, 8.0000])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([4.8008, 9.2031, 8.0000], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([23.0438, 84.6687, 64.0000])

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor

tensor([14.4000, 55.2000, 72.0000])

### Getting information from tensors
to get right dtype -> tensor.dtype
to get right shape -> tensor.shape
to get right device -> tensor.device

In [ ]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7066, 0.7992, 0.3883, 0.3581],
        [0.5398, 0.9955, 0.7618, 0.4243],
        [0.2449, 0.8676, 0.8690, 0.8770]])

In [ ]:
some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [ ]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7066, 0.7992, 0.3883, 0.3581],
        [0.5398, 0.9955, 0.7618, 0.4243],
        [0.2449, 0.8676, 0.8690, 0.8770]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
 # Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# Subtract by 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [ ]:
tensor / 7

tensor([0.1429, 0.2857, 0.4286])

### MATRIX multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix Multiplication(common one) (dot product)



In [ ]:
# Element wise muliplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)


tensor(14)
CPU times: user 2.78 ms, sys: 0 ns, total: 2.78 ms
Wall time: 2.88 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.23 ms, sys: 12 µs, total: 1.24 ms
Wall time: 1.23 ms


tensor(14)

In [ ]:
### One of the most common errors in deep learning: shape errors

In [ ]:
torch.matmul(torch.rand(30,20), torch.rand(20,20)).shape

torch.Size([30, 20])

To fix our tensor shape issues, we can manipulate the shape of our tensor using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_A = torch.tensor([[1,2],[4,5],[6,7]])

In [ ]:
tensor_B = torch.tensor([[12,9],[3,2],[8,1]])

In [ ]:
tensor_A, tensor_A.shape

(tensor([[1, 2],
         [4, 5],
         [6, 7]]),
 torch.Size([3, 2]))

In [ ]:
tensor_A.T, tensor_B.T.shape

(tensor([[1, 4, 6],
         [2, 5, 7]]),
 torch.Size([2, 3]))

In [ ]:
# The matrix multiplication operation works when tensor_A is tranposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 30,   7,  10],
        [ 93,  22,  37],
        [135,  32,  55]])

Output shape: torch.Size([3, 3])


Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqeezinf tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[9., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
# z[0] = 5
z[:, 0] = 9
z,x

(tensor([[9., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([9., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top each others
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[9., 2., 3., 4., 5., 6., 7., 8., 9.],
        [9., 2., 3., 4., 5., 6., 7., 8., 9.],
        [9., 2., 3., 4., 5., 6., 7., 8., 9.],
        [9., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
#  torch.squeeze() - removes all single dimensions from a target tensor
x_reshaped

tensor([[9., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_squeezed =  x_reshaped.squeeze()

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
# torch.unsqueeze - adds a single dimension to a target tensor ar a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew Tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([9., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New Tensor: tensor([[9., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) #[height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channel, height, width]
x_permuted

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


tensor([[[0.0394, 0.1554, 0.5524,  ..., 0.2114, 0.5167, 0.5076],
         [0.4643, 0.0489, 0.5019,  ..., 0.4487, 0.2029, 0.9182],
         [0.3607, 0.8547, 0.0767,  ..., 0.5096, 0.1836, 0.7028],
         ...,
         [0.2790, 0.3338, 0.1234,  ..., 0.9815, 0.1155, 0.6376],
         [0.1724, 0.0142, 0.9427,  ..., 0.1609, 0.5555, 0.8669],
         [0.4344, 0.6096, 0.2620,  ..., 0.4348, 0.3849, 0.8714]],

        [[0.9878, 0.8404, 0.7880,  ..., 0.1061, 0.1010, 0.0783],
         [0.2118, 0.6111, 0.0282,  ..., 0.2403, 0.3361, 0.5762],
         [0.2539, 0.7276, 0.6832,  ..., 0.4777, 0.9749, 0.8378],
         ...,
         [0.0514, 0.5674, 0.1925,  ..., 0.0108, 0.1377, 0.7372],
         [0.0721, 0.4299, 0.7187,  ..., 0.5763, 0.5292, 0.8355],
         [0.4222, 0.3565, 0.0480,  ..., 0.7260, 0.9708, 0.3095]],

        [[0.8111, 0.3584, 0.1578,  ..., 0.1199, 0.6868, 0.8753],
         [0.8720, 0.4713, 0.7815,  ..., 0.8383, 0.4928, 0.9402],
         [0.3224, 0.6514, 0.7211,  ..., 0.0037, 0.6183, 0.

In [ ]:
x_original

tensor([[[0.0394, 0.9878, 0.8111],
         [0.1554, 0.8404, 0.3584],
         [0.5524, 0.7880, 0.1578],
         ...,
         [0.2114, 0.1061, 0.1199],
         [0.5167, 0.1010, 0.6868],
         [0.5076, 0.0783, 0.8753]],

        [[0.4643, 0.2118, 0.8720],
         [0.0489, 0.6111, 0.4713],
         [0.5019, 0.0282, 0.7815],
         ...,
         [0.4487, 0.2403, 0.8383],
         [0.2029, 0.3361, 0.4928],
         [0.9182, 0.5762, 0.9402]],

        [[0.3607, 0.2539, 0.3224],
         [0.8547, 0.7276, 0.6514],
         [0.0767, 0.6832, 0.7211],
         ...,
         [0.5096, 0.4777, 0.0037],
         [0.1836, 0.9749, 0.6183],
         [0.7028, 0.8378, 0.6306]],

        ...,

        [[0.2790, 0.0514, 0.2620],
         [0.3338, 0.5674, 0.6617],
         [0.1234, 0.1925, 0.2693],
         ...,
         [0.9815, 0.0108, 0.5620],
         [0.1155, 0.1377, 0.6963],
         [0.6376, 0.7372, 0.1126]],

        [[0.1724, 0.0721, 0.3576],
         [0.0142, 0.4299, 0.1505],
         [0.

In [ ]:
x_original[0,0,0] = 345676543

In [ ]:
x_permuted

tensor([[[3.4568e+08, 1.5538e-01, 5.5244e-01,  ..., 2.1141e-01,
          5.1666e-01, 5.0762e-01],
         [4.6428e-01, 4.8879e-02, 5.0185e-01,  ..., 4.4871e-01,
          2.0289e-01, 9.1823e-01],
         [3.6075e-01, 8.5468e-01, 7.6664e-02,  ..., 5.0964e-01,
          1.8361e-01, 7.0281e-01],
         ...,
         [2.7900e-01, 3.3380e-01, 1.2344e-01,  ..., 9.8153e-01,
          1.1549e-01, 6.3765e-01],
         [1.7244e-01, 1.4177e-02, 9.4270e-01,  ..., 1.6092e-01,
          5.5551e-01, 8.6694e-01],
         [4.3437e-01, 6.0959e-01, 2.6200e-01,  ..., 4.3483e-01,
          3.8493e-01, 8.7144e-01]],

        [[9.8775e-01, 8.4041e-01, 7.8805e-01,  ..., 1.0613e-01,
          1.0101e-01, 7.8262e-02],
         [2.1183e-01, 6.1110e-01, 2.8246e-02,  ..., 2.4030e-01,
          3.3607e-01, 5.7618e-01],
         [2.5390e-01, 7.2764e-01, 6.8319e-01,  ..., 4.7768e-01,
          9.7494e-01, 8.3776e-01],
         ...,
         [5.1393e-02, 5.6736e-01, 1.9249e-01,  ..., 1.0793e-02,
          1.377

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPY